spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/logDb;
    username: root
    password: password
    webAllowOthers: true

  jpa:
    hibernate:
      ddl-auto:
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect


logging:
  level:
    org.springframework.security: trace